# Generated by Django 2.1.1 on 2018-10-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('feedback', models.TextField()),
                ('response', models.CharField(choices=[('seen', 'Seen'), ('notseen', 'notseen')], default='notseen', max_length=9)),
            ],
        ),
    ]
